services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "StrongPassword@1"
    ports:
      - "1488:1433"
    volumes:
      - sqlvol:/var/opt/mssql
  
  backend-service:
    container_name: backend-service
    build:
      context: ./src/MPA.API/
      dockerfile: Dockerfile
    ports:
      - "1501:8080"

volumes:
  sqlvol: