services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "StrongPassword@1"
    ports:
      - "1488:1433"
    volumes:
      - sqltest:/var/opt/mssql
  
  backend-service:
    container_name: backend-service
    build:
      context: ./src
      dockerfile: MPA.API/Dockerfile
    ports:
      - "1501:8080"
    environment:
    - OpenAI__ApiKey=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

volumes:
  sqltest:

  
